### ISSUE TITLE
[BUG] Warning when ruing csv test

### ISSUE THREAD

**Issue by afender** [rapidsai/dask-cugraph#15]
```
(cugraph_dev) afender@strata3:~/sw/dask-cugraph$ pytest
================================================================================= test session starts ==================================================================================
platform linux -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /home/afender/sw/dask-cugraph
collected 2 items                                                                                                                                                                      

dask_cugraph/tests/test_csv_pagerank.py .                                                                                                                                        [ 50%]
dask_cugraph/tests/test_dask_cugraph.py .                                                                                                                                        [100%]

=================================================================================== warnings summary ===================================================================================
/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/heapdict.py:11
  /home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/heapdict.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class heapdict(collections.MutableMapping):

dask_cugraph/tests/test_csv_pagerank.py::test_one_csv_file_pagerank
  /home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
    return f(*args, **kwds)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================================= 2 passed, 2 warnings in 9.73 seconds =========================================================================
--- Logging error ---
Traceback (most recent call last):
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/process.py", line 335, in _cleanup_dangling
    logger.warning("reaping stray process %s" % (proc,))
Message: 'reaping stray process <ForkServerProcess(ForkServerProcess-5, started daemon)>'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/process.py", line 335, in _cleanup_dangling
    logger.warning("reaping stray process %s" % (proc,))
Message: 'reaping stray process <ForkServerProcess(ForkServerProcess-3, started daemon)>'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/process.py", line 335, in _cleanup_dangling
    logger.warning("reaping stray process %s" % (proc,))
Message: 'reaping stray process <ForkServerProcess(ForkServerProcess-1, started daemon)>'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/process.py", line 335, in _cleanup_dangling
    logger.warning("reaping stray process %s" % (proc,))
Message: 'reaping stray process <ForkServerProcess(ForkServerProcess-6, started daemon)>'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/process.py", line 335, in _cleanup_dangling
    logger.warning("reaping stray process %s" % (proc,))
Message: 'reaping stray process <ForkServerProcess(ForkServerProcess-4, started daemon)>'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/process.py", line 335, in _cleanup_dangling
    logger.warning("reaping stray process %s" % (proc,))
Message: 'reaping stray process <ForkServerProcess(ForkServerProcess-2, started daemon)>'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/utils.py", line 410, in run_loop
    loop.start()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/process.py", line 122, in _on_exit
    self._exit_callback(self)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/nanny.py", line 457, in _on_exit
    self.mark_stopped()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/nanny.py", line 481, in mark_stopped
    logger.warning(msg)
Message: 'Worker process 30704 was killed by unknown signal'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/utils.py", line 410, in run_loop
    loop.start()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/process.py", line 122, in _on_exit
    self._exit_callback(self)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/nanny.py", line 457, in _on_exit
    self.mark_stopped()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/nanny.py", line 481, in mark_stopped
    logger.warning(msg)
Message: 'Worker process 30571 was killed by unknown signal'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/_pytest/capture.py", line 441, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/utils.py", line 410, in run_loop
    loop.start()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/process.py", line 122, in _on_exit
    self._exit_callback(self)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/nanny.py", line 457, in _on_exit
    self.mark_stopped()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/distributed/nanny.py", line 481, in mark_stopped
    logger.warning(msg)
Message: 'Worker process 30573 was killed by unknown signal'
Arguments: ()
```

**Comment by afender** [comment]
https://nvidia.slack.com/archives/CENC8QZ63/p1561657518136800

**Comment by afender** [comment]
@Iroy30 I recall you filled a dask-cuda issue for this, correct? Please add the link here.

**Comment by afender** [comment]
@Iroy30 and I cannot repro. Closing
